-- 1. Sync Achievement Definitions
INSERT INTO achievements (key, name, description, type)
VALUES
  ('veteran_1', 'Veteran I', 'Play 1 games', 'milestone'),
  ('veteran_2', 'Veteran II', 'Play 5 games', 'milestone'),
  ('veteran_3', 'Veteran III', 'Play 10 games', 'milestone'),
  ('veteran_4', 'Veteran IV', 'Play 25 games', 'milestone'),
  ('veteran_5', 'Veteran V', 'Play 50 games', 'milestone'),
  ('veteran_6', 'Veteran VI', 'Play 100 games', 'milestone'),
  ('veteran_7', 'Veteran VII', 'Play 250 games', 'milestone'),
  ('veteran_8', 'Veteran VIII', 'Play 500 games', 'milestone'),
  ('veteran_9', 'Veteran IX', 'Play 1000 games', 'milestone'),
  ('survivor_1', 'Survivor I', 'Survive total 5 min', 'milestone'),
  ('survivor_2', 'Survivor II', 'Survive total 15 min', 'milestone'),
  ('survivor_3', 'Survivor III', 'Survive total 30 min', 'milestone'),
  ('survivor_4', 'Survivor IV', 'Survive total 1 hour', 'milestone'),
  ('survivor_5', 'Survivor V', 'Survive total 2 hours', 'milestone'),
  ('survivor_6', 'Survivor VI', 'Survive total 5 hours', 'milestone'),
  ('survivor_7', 'Survivor VII', 'Survive total 10 hours', 'milestone'),
  ('survivor_8', 'Survivor VIII', 'Survive total 24 hours', 'milestone'),
  ('collector_1', 'Collector I', 'Collect 10 bonuses', 'milestone'),
  ('collector_2', 'Collector II', 'Collect 50 bonuses', 'milestone'),
  ('collector_3', 'Collector III', 'Collect 150 bonuses', 'milestone'),
  ('collector_4', 'Collector IV', 'Collect 300 bonuses', 'milestone'),
  ('collector_5', 'Collector V', 'Collect 750 bonuses', 'milestone'),
  ('collector_6', 'Collector VI', 'Collect 1500 bonuses', 'milestone'),
  ('collector_7', 'Collector VII', 'Collect 3000 bonuses', 'milestone'),
  ('ghost_1', 'Ghost I', 'Get 25 near misses', 'milestone'),
  ('ghost_2', 'Ghost II', 'Get 100 near misses', 'milestone'),
  ('ghost_3', 'Ghost III', 'Get 300 near misses', 'milestone'),
  ('ghost_4', 'Ghost IV', 'Get 750 near misses', 'milestone'),
  ('ghost_5', 'Ghost V', 'Get 2000 near misses', 'milestone'),
  ('ghost_6', 'Ghost VI', 'Get 5000 near misses', 'milestone'),
  ('ghost_7', 'Ghost VII', 'Get 10000 near misses', 'milestone'),
  ('hard_boiled_1', 'Hard Boiled I', 'Play 5 hard runs', 'milestone'),
  ('hard_boiled_2', 'Hard Boiled II', 'Play 15 hard runs', 'milestone'),
  ('hard_boiled_3', 'Hard Boiled III', 'Play 30 hard runs', 'milestone'),
  ('hard_boiled_4', 'Hard Boiled IV', 'Play 50 hard runs', 'milestone'),
  ('hard_boiled_5', 'Hard Boiled V', 'Play 100 hard runs', 'milestone'),
  ('hard_boiled_6', 'Hard Boiled VI', 'Play 250 hard runs', 'milestone'),
  ('wealthy_1', 'Wealthy I', 'Accumulate 1000 total points', 'milestone'),
  ('wealthy_2', 'Wealthy II', 'Accumulate 5000 total points', 'milestone'),
  ('wealthy_3', 'Wealthy III', 'Accumulate 25000 total points', 'milestone'),
  ('wealthy_4', 'Wealthy IV', 'Accumulate 100000 total points', 'milestone'),
  ('wealthy_5', 'Wealthy V', 'Accumulate 500000 total points', 'milestone'),
  ('wealthy_6', 'Wealthy VI', 'Accumulate 1000000 total points', 'milestone'),
  ('wealthy_7', 'Wealthy VII', 'Accumulate 5000000 total points', 'milestone'),
  ('wealthy_8', 'Wealthy VIII', 'Accumulate 10000000 total points', 'milestone'),
  ('high_score_1', 'High Score I', 'Reach 100 points in one run', 'milestone'),
  ('high_score_2', 'High Score II', 'Reach 500 points in one run', 'milestone'),
  ('high_score_3', 'High Score III', 'Reach 1000 points in one run', 'milestone'),
  ('high_score_4', 'High Score IV', 'Reach 2500 points in one run', 'milestone'),
  ('high_score_5', 'High Score V', 'Reach 5000 points in one run', 'milestone'),
  ('high_score_6', 'High Score VI', 'Reach 10000 points in one run', 'milestone'),
  ('first_blood', 'First Blood', 'Play your first game', 'single_run'),
  ('minuteman', 'Minuteman', 'Survive 60s in one run', 'single_run'),
  ('untouchable', 'Untouchable', 'Survive 30s with 0 near misses', 'single_run'),
  ('danger_zone', 'Danger Zone', '15+ near misses in one run', 'single_run'),
  ('hoarder', 'Hoarder', 'Collect 6+ bonuses in one run', 'single_run'),
  ('hard_debut', 'Hard Debut', 'Survive 30s on Hard difficulty', 'single_run'),
  ('pacifist', 'Pacifist', 'Survive 45s collecting no bonuses', 'single_run'),
  ('matrix', 'The Matrix', '10 near misses in 5 seconds', 'single_run'),
  ('combo_king', 'Combo King', 'Bank 500+ points in one combo', 'single_run'),
  ('slowmo_junkie', 'Slow-mo Junkie', 'Collect 4 slow-mo bonuses in one run', 'single_run'),
  ('shield_master', 'Shield Master', 'Collect 3 shield bonuses in one run', 'single_run'),
  ('clean_slate', 'Clean Slate', 'Use 3 screenclears in one run', 'single_run'),
  ('tiny_but_mighty', 'Tiny but Mighty', 'Collect 3 shrink bonuses in one run', 'single_run'),
  ('jack_of_all_trades', 'Jack of All Trades', 'Collect all 4 bonus types in one run', 'single_run'),
  ('near_death', 'Near-Death Experience', 'Die with 1000+ score pending', 'single_run'),
  ('early_departure', 'Early Departure', 'Die within 10 seconds', 'single_run')
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  type = EXCLUDED.type;

-- 2. Update stats aggregation function

CREATE OR REPLACE FUNCTION get_user_stats(p_user_id uuid)
RETURNS TABLE (
    total_runs bigint,
    total_score numeric,
    best_score_easy numeric,
    best_score_normal numeric,
    best_score_hard numeric,
    avg_score_easy numeric,
    avg_score_normal numeric,
    avg_score_hard numeric,
    total_near_misses bigint,
    total_bonuses bigint,
    best_combo_score numeric,
    total_elapsed_ms bigint,
    avg_elapsed_ms numeric,
    hard_runs_count bigint,
    deaths_ball bigint,
    deaths_bullet bigint,
    deaths_shard bigint,
    deaths_tracker bigint
) LANGUAGE plpgsql SECURITY DEFINER STABLE AS $$
BEGIN
    RETURN QUERY
    SELECT
        COUNT(*)::bigint AS total_runs,
        COALESCE(SUM(score), 0)::numeric AS total_score,
        MAX(CASE WHEN difficulty = 'easy' THEN score ELSE 0 END)::numeric AS best_score_easy,
        MAX(CASE WHEN difficulty = 'normal' THEN score ELSE 0 END)::numeric AS best_score_normal,
        MAX(CASE WHEN difficulty = 'hard' THEN score ELSE 0 END)::numeric AS best_score_hard,
        COALESCE(AVG(CASE WHEN difficulty = 'easy' THEN score END), 0)::numeric AS avg_score_easy,
        COALESCE(AVG(CASE WHEN difficulty = 'normal' THEN score END), 0)::numeric AS avg_score_normal,
        COALESCE(AVG(CASE WHEN difficulty = 'hard' THEN score END), 0)::numeric AS avg_score_hard,
        SUM(near_misses)::bigint AS total_near_misses,
        SUM(bonuses_collected)::bigint AS total_bonuses,
        MAX(combo_score)::numeric AS best_combo_score,
        SUM(elapsed_ms)::bigint AS total_elapsed_ms,
        COALESCE(AVG(elapsed_ms), 0)::numeric AS avg_elapsed_ms,
        COUNT(*) FILTER (WHERE difficulty = 'hard')::bigint AS hard_runs_count,
        COUNT(*) FILTER (WHERE death_cause = 'ball')::bigint AS deaths_ball,
        COUNT(*) FILTER (WHERE death_cause = 'bullet')::bigint AS deaths_bullet,
        COUNT(*) FILTER (WHERE death_cause = 'shard')::bigint AS deaths_shard,
        COUNT(*) FILTER (WHERE death_cause = 'tracker')::bigint AS deaths_tracker
    FROM runs
    WHERE user_id = p_user_id;
END;
$$;
